# Generated by Django 4.2.5 on 2025-09-26 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título da série', max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(help_text='Descrição da série', verbose_name='Descrição')),
                ('ano', models.PositiveIntegerField(help_text='Ano em que a série foi lançada', verbose_name='Ano de Lançamento')),
                ('genero', models.CharField(choices=[('acao', 'Ação'), ('aventura', 'Aventura'), ('comedia', 'Comédia'), ('drama', 'Drama'), ('fantasia', 'Fantasia'), ('ficcao', 'Ficção Científica'), ('horror', 'Horror'), ('romance', 'Romance'), ('suspense', 'Suspense'), ('terror', 'Terror'), ('thriller', 'Thriller'), ('documentario', 'Documentário'), ('animacao', 'Animação'), ('outros', 'Outros')], help_text='Gênero da série', max_length=20, verbose_name='Gênero')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem da série', null=True, upload_to='series/', verbose_name='Imagem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('criado_por', models.ForeignKey(help_text='Usuário que criou a série', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
